[build]
  base = "client"
  command = "npm install && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "16"
  REACT_APP_API_URL = "/.netlify/functions/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[functions]
  directory = "server/functions"
  node_bundler = "esbuild"
